services:
  - type: web
    name: chess-backend
    runtime: node
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: apt-get update && apt-get install -y stockfish && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://chess-app-jii7.onrender.com

  - type: web
    name: chess-frontend
    runtime: static
    region: oregon
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://chess-gf05.onrender.com
      - key: VITE_WS_URL
        value: wss://chess-gf05.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html